services:
  meli_client:
    build: client
    command: yarn start
    networks:
      - meli-network
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/app
    environment:
      - REACT_APP_BASE_URL=http://192.168.0.106:3333

  meli_server:
    build: server
    command: yarn start:dev
    networks:
      - meli-network
    ports:
      - '3333:3333'
    volumes:
      - ./server:/usr/app
    environment:
      - JWT_EXPIRATION_TIME=7d
      - JWT_SECRET=iyCrZCJ4oALf$db5XQ4F7B

networks:
  meli-network:
    external: true
    driver: bridge
